logging:
  level:
#    org.mybatis: DEBUG
    com:
      example:
        demo: info
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss.SSS}){yellow} %clr(${PID:-}){green} %magenta([%thread])
      %highlight([%-5level]) %clr(%-40.40logger{39}){cyan} %msg%n'    

spring:
    
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
#    url: jdbc:postgresql://localhost:5432/gst_db?currentSchema=schema_test
    url: jdbc:postgresql://localhost:5432/gst_db?currentSchema=schema_dev
    
  sql:
    init:
      mode: never #pour activer l'initialisation de la bdd, changer le mode en always
      schema-locations: classpath:schema-dev.sql
#      schema-locations: classpath:schema-test.sql
      data-locations: classpath:data-dev.sql
#      data-locations: classpath:data-test.sql
    
  mail:
    host: smtp.gmail.com
    password: yuzo hnbp xvfl xxyt
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
    username: hamza.h93290@gmail.com
    
token:
  expiration:
    duration: 900 # durée de 900 secondes (15 min)

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

refresh:
  token:
    expiration:
      duration: 1800 # durée de 1800 secondes (30 min)

reset:
  password:
    claim:
      expiration:
        duration: 15 # durée de 15 minutes
        
mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mybatis/xml/mappers/*.xml
        
